server:
  port: 8081

spring:
  application:
    name: cleanarchitecturebase
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:file:/home/anderson-elit/hospitaldb
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console.enabled: true

